---
- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Deploy common MOTD
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
  notify: Reload system message
